apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: DaemonSet
      name: kubenpu
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: accel
          mountPath: /dev/accel
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: accel
          hostPath:
            path: /dev/accel
            type: Directory
