// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfDeviceKey struct {
	_     structs.HostLayout
	Major uint32
	Minor uint32
}

type bpfEvent struct {
	_         structs.HostLayout
	Timestamp uint64
	CgroupId  uint64
	Tgid      uint32
	Cmd       uint32
	Minor     uint32
	Major     uint16
	Kind      uint8
	Pad       [1]uint8
}

type bpfIoctlKey struct {
	_        structs.HostLayout
	VendorId uint32
	Nr       uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapDevices       = "devices"
	bpfMapEvents        = "events"
	bpfMapIoctls        = "ioctls"
	bpfProgKubenpuIoctl = "kubenpu_ioctl"
	bpfVarUnusedEvent   = "unused_event"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KubenpuIoctl *ebpf.ProgramSpec `ebpf:"kubenpu_ioctl"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Devices *ebpf.MapSpec `ebpf:"devices"`
	Events  *ebpf.MapSpec `ebpf:"events"`
	Ioctls  *ebpf.MapSpec `ebpf:"ioctls"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Devices *ebpf.Map `ebpf:"devices"`
	Events  *ebpf.Map `ebpf:"events"`
	Ioctls  *ebpf.Map `ebpf:"ioctls"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Devices,
		m.Events,
		m.Ioctls,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KubenpuIoctl *ebpf.Program `ebpf:"kubenpu_ioctl"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KubenpuIoctl,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
